version: "3.9"

services:
  dash:
    build:
      context: .
      dockerfile: Dockerfile
    image: a3_car_price_prediction:latest
    ports:
      - "8060:8080"
    volumes:
      - ./code:/root/code
      - ./_mlflow/mlruns:/mlflow/mlruns
    command: ["python3", "/root/code/app.py"]
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow.ml.brain.cs.ait.ac.th/"
      MLFLOW_TRACKING_USERNAME: "admin"
      MLFLOW_TRACKING_PASSWORD: "password"
      PYTHONPATH: "/root/code"
    networks:
      - car-network

networks:
  car-network:
    driver: bridge